// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette;

/** Abstract Visitor */

public class AbstractVisitor<R,A> implements AllVisitor<R,A> {
    /* Prog */
    public R visit(jlc.lib.javalette.Absyn.Program p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.Prog p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* TopDef */
    public R visit(jlc.lib.javalette.Absyn.FnDef p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.TopDef p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* Arg */
    public R visit(jlc.lib.javalette.Absyn.Argument p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.Arg p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* Blk */
    public R visit(jlc.lib.javalette.Absyn.Block p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.Blk p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* Stmt */
    public R visit(jlc.lib.javalette.Absyn.Empty p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.BStmt p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Decl p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Ass p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ArrAss p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ArrAssExpr p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ForEach p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ArrIncr p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ArrDecr p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Incr p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Decr p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Ret p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.VRet p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Cond p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.CondElse p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.While p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.SExp p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.Stmt p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* Item */
    public R visit(jlc.lib.javalette.Absyn.NoInit p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Init p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.Item p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* BaseType */
    public R visit(jlc.lib.javalette.Absyn.Int p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Doub p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Bool p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Void p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.BaseType p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* Type */
    public R visit(jlc.lib.javalette.Absyn.TypeBase p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ArrType p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Fun p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.Type p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* Expr */
    public R visit(jlc.lib.javalette.Absyn.EVar p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ELitInt p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ELitDoub p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ELitTrue p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ELitFalse p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.EApp p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.EString p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ArrIndex p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ArrLen p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.NewArr p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Neg p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Not p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.EMul p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.EAdd p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.ERel p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.EAnd p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.EOr p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.Expr p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* AddOp */
    public R visit(jlc.lib.javalette.Absyn.Plus p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Minus p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.AddOp p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* MulOp */
    public R visit(jlc.lib.javalette.Absyn.Times p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Div p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.Mod p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.MulOp p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }
    /* RelOp */
    public R visit(jlc.lib.javalette.Absyn.LTH p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.LE p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.GTH p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.GE p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.EQU p, A arg) { return visitDefault(p, arg); }
    public R visit(jlc.lib.javalette.Absyn.NE p, A arg) { return visitDefault(p, arg); }
    public R visitDefault(jlc.lib.javalette.Absyn.RelOp p, A arg) {
      throw new IllegalArgumentException(this.getClass().getName() + ": " + p);
    }

}
