// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette;

/** All Visitor */

public interface AllVisitor<R,A> extends
  jlc.lib.javalette.Absyn.Prog.Visitor<R,A>,
  jlc.lib.javalette.Absyn.TopDef.Visitor<R,A>,
  jlc.lib.javalette.Absyn.Arg.Visitor<R,A>,
  jlc.lib.javalette.Absyn.Blk.Visitor<R,A>,
  jlc.lib.javalette.Absyn.Stmt.Visitor<R,A>,
  jlc.lib.javalette.Absyn.Item.Visitor<R,A>,
  jlc.lib.javalette.Absyn.BaseType.Visitor<R,A>,
  jlc.lib.javalette.Absyn.Type.Visitor<R,A>,
  jlc.lib.javalette.Absyn.Expr.Visitor<R,A>,
  jlc.lib.javalette.Absyn.AddOp.Visitor<R,A>,
  jlc.lib.javalette.Absyn.MulOp.Visitor<R,A>,
  jlc.lib.javalette.Absyn.RelOp.Visitor<R,A>
{}
