// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette;
/** Composition Visitor
*/

public class ComposVisitor<A> implements
  jlc.lib.javalette.Absyn.Prog.Visitor<jlc.lib.javalette.Absyn.Prog,A>,
  jlc.lib.javalette.Absyn.TopDef.Visitor<jlc.lib.javalette.Absyn.TopDef,A>,
  jlc.lib.javalette.Absyn.Arg.Visitor<jlc.lib.javalette.Absyn.Arg,A>,
  jlc.lib.javalette.Absyn.Blk.Visitor<jlc.lib.javalette.Absyn.Blk,A>,
  jlc.lib.javalette.Absyn.Stmt.Visitor<jlc.lib.javalette.Absyn.Stmt,A>,
  jlc.lib.javalette.Absyn.Item.Visitor<jlc.lib.javalette.Absyn.Item,A>,
  jlc.lib.javalette.Absyn.Type.Visitor<jlc.lib.javalette.Absyn.Type,A>,
  jlc.lib.javalette.Absyn.Expr.Visitor<jlc.lib.javalette.Absyn.Expr,A>,
  jlc.lib.javalette.Absyn.AddOp.Visitor<jlc.lib.javalette.Absyn.AddOp,A>,
  jlc.lib.javalette.Absyn.MulOp.Visitor<jlc.lib.javalette.Absyn.MulOp,A>,
  jlc.lib.javalette.Absyn.RelOp.Visitor<jlc.lib.javalette.Absyn.RelOp,A>
{
    /* Prog */
    public jlc.lib.javalette.Absyn.Prog visit(jlc.lib.javalette.Absyn.Program p, A arg)
    {
      jlc.lib.javalette.Absyn.ListTopDef listtopdef_ = new jlc.lib.javalette.Absyn.ListTopDef();
      for (jlc.lib.javalette.Absyn.TopDef x : p.listtopdef_)
      {
        listtopdef_.add(x.accept(this,arg));
      }
      return new jlc.lib.javalette.Absyn.Program(listtopdef_);
    }

    /* TopDef */
    public jlc.lib.javalette.Absyn.TopDef visit(jlc.lib.javalette.Absyn.FnDef p, A arg)
    {
      jlc.lib.javalette.Absyn.Type type_ = p.type_.accept(this, arg);
      String ident_ = p.ident_;
      jlc.lib.javalette.Absyn.ListArg listarg_ = new jlc.lib.javalette.Absyn.ListArg();
      for (jlc.lib.javalette.Absyn.Arg x : p.listarg_)
      {
        listarg_.add(x.accept(this,arg));
      }
      jlc.lib.javalette.Absyn.Blk blk_ = p.blk_.accept(this, arg);
      return new jlc.lib.javalette.Absyn.FnDef(type_, ident_, listarg_, blk_);
    }

    /* Arg */
    public jlc.lib.javalette.Absyn.Arg visit(jlc.lib.javalette.Absyn.Argument p, A arg)
    {
      jlc.lib.javalette.Absyn.Type type_ = p.type_.accept(this, arg);
      String ident_ = p.ident_;
      return new jlc.lib.javalette.Absyn.Argument(type_, ident_);
    }

    /* Blk */
    public jlc.lib.javalette.Absyn.Blk visit(jlc.lib.javalette.Absyn.Block p, A arg)
    {
      jlc.lib.javalette.Absyn.ListStmt liststmt_ = new jlc.lib.javalette.Absyn.ListStmt();
      for (jlc.lib.javalette.Absyn.Stmt x : p.liststmt_)
      {
        liststmt_.add(x.accept(this,arg));
      }
      return new jlc.lib.javalette.Absyn.Block(liststmt_);
    }

    /* Stmt */
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.Empty p, A arg)
    {
      return new jlc.lib.javalette.Absyn.Empty();
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.BStmt p, A arg)
    {
      jlc.lib.javalette.Absyn.Blk blk_ = p.blk_.accept(this, arg);
      return new jlc.lib.javalette.Absyn.BStmt(blk_);
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.Decl p, A arg)
    {
      jlc.lib.javalette.Absyn.Type type_ = p.type_.accept(this, arg);
      jlc.lib.javalette.Absyn.ListItem listitem_ = new jlc.lib.javalette.Absyn.ListItem();
      for (jlc.lib.javalette.Absyn.Item x : p.listitem_)
      {
        listitem_.add(x.accept(this,arg));
      }
      return new jlc.lib.javalette.Absyn.Decl(type_, listitem_);
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.Ass p, A arg)
    {
      String ident_ = p.ident_;
      jlc.lib.javalette.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new jlc.lib.javalette.Absyn.Ass(ident_, expr_);
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.Incr p, A arg)
    {
      String ident_ = p.ident_;
      return new jlc.lib.javalette.Absyn.Incr(ident_);
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.Decr p, A arg)
    {
      String ident_ = p.ident_;
      return new jlc.lib.javalette.Absyn.Decr(ident_);
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.Ret p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new jlc.lib.javalette.Absyn.Ret(expr_);
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.VRet p, A arg)
    {
      return new jlc.lib.javalette.Absyn.VRet();
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.Cond p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      jlc.lib.javalette.Absyn.Stmt stmt_ = p.stmt_.accept(this, arg);
      return new jlc.lib.javalette.Absyn.Cond(expr_, stmt_);
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.CondElse p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      jlc.lib.javalette.Absyn.Stmt stmt_1 = p.stmt_1.accept(this, arg);
      jlc.lib.javalette.Absyn.Stmt stmt_2 = p.stmt_2.accept(this, arg);
      return new jlc.lib.javalette.Absyn.CondElse(expr_, stmt_1, stmt_2);
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.While p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      jlc.lib.javalette.Absyn.Stmt stmt_ = p.stmt_.accept(this, arg);
      return new jlc.lib.javalette.Absyn.While(expr_, stmt_);
    }
    public jlc.lib.javalette.Absyn.Stmt visit(jlc.lib.javalette.Absyn.SExp p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new jlc.lib.javalette.Absyn.SExp(expr_);
    }

    /* Item */
    public jlc.lib.javalette.Absyn.Item visit(jlc.lib.javalette.Absyn.NoInit p, A arg)
    {
      String ident_ = p.ident_;
      return new jlc.lib.javalette.Absyn.NoInit(ident_);
    }
    public jlc.lib.javalette.Absyn.Item visit(jlc.lib.javalette.Absyn.Init p, A arg)
    {
      String ident_ = p.ident_;
      jlc.lib.javalette.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new jlc.lib.javalette.Absyn.Init(ident_, expr_);
    }

    /* Type */
    public jlc.lib.javalette.Absyn.Type visit(jlc.lib.javalette.Absyn.Int p, A arg)
    {
      return new jlc.lib.javalette.Absyn.Int();
    }
    public jlc.lib.javalette.Absyn.Type visit(jlc.lib.javalette.Absyn.Doub p, A arg)
    {
      return new jlc.lib.javalette.Absyn.Doub();
    }
    public jlc.lib.javalette.Absyn.Type visit(jlc.lib.javalette.Absyn.Bool p, A arg)
    {
      return new jlc.lib.javalette.Absyn.Bool();
    }
    public jlc.lib.javalette.Absyn.Type visit(jlc.lib.javalette.Absyn.Void p, A arg)
    {
      return new jlc.lib.javalette.Absyn.Void();
    }
    public jlc.lib.javalette.Absyn.Type visit(jlc.lib.javalette.Absyn.Fun p, A arg)
    {
      jlc.lib.javalette.Absyn.Type type_ = p.type_.accept(this, arg);
      jlc.lib.javalette.Absyn.ListType listtype_ = new jlc.lib.javalette.Absyn.ListType();
      for (jlc.lib.javalette.Absyn.Type x : p.listtype_)
      {
        listtype_.add(x.accept(this,arg));
      }
      return new jlc.lib.javalette.Absyn.Fun(type_, listtype_);
    }

    /* Expr */
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.EVar p, A arg)
    {
      String ident_ = p.ident_;
      return new jlc.lib.javalette.Absyn.EVar(ident_);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.ELitInt p, A arg)
    {
      Integer integer_ = p.integer_;
      return new jlc.lib.javalette.Absyn.ELitInt(integer_);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.ELitDoub p, A arg)
    {
      Double double_ = p.double_;
      return new jlc.lib.javalette.Absyn.ELitDoub(double_);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.ELitTrue p, A arg)
    {
      return new jlc.lib.javalette.Absyn.ELitTrue();
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.ELitFalse p, A arg)
    {
      return new jlc.lib.javalette.Absyn.ELitFalse();
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.EApp p, A arg)
    {
      String ident_ = p.ident_;
      jlc.lib.javalette.Absyn.ListExpr listexpr_ = new jlc.lib.javalette.Absyn.ListExpr();
      for (jlc.lib.javalette.Absyn.Expr x : p.listexpr_)
      {
        listexpr_.add(x.accept(this,arg));
      }
      return new jlc.lib.javalette.Absyn.EApp(ident_, listexpr_);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.EString p, A arg)
    {
      String string_ = p.string_;
      return new jlc.lib.javalette.Absyn.EString(string_);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.Neg p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new jlc.lib.javalette.Absyn.Neg(expr_);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.Not p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_ = p.expr_.accept(this, arg);
      return new jlc.lib.javalette.Absyn.Not(expr_);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.EMul p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      jlc.lib.javalette.Absyn.MulOp mulop_ = p.mulop_.accept(this, arg);
      jlc.lib.javalette.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new jlc.lib.javalette.Absyn.EMul(expr_1, mulop_, expr_2);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.EAdd p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      jlc.lib.javalette.Absyn.AddOp addop_ = p.addop_.accept(this, arg);
      jlc.lib.javalette.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new jlc.lib.javalette.Absyn.EAdd(expr_1, addop_, expr_2);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.ERel p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      jlc.lib.javalette.Absyn.RelOp relop_ = p.relop_.accept(this, arg);
      jlc.lib.javalette.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new jlc.lib.javalette.Absyn.ERel(expr_1, relop_, expr_2);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.EAnd p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      jlc.lib.javalette.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new jlc.lib.javalette.Absyn.EAnd(expr_1, expr_2);
    }
    public jlc.lib.javalette.Absyn.Expr visit(jlc.lib.javalette.Absyn.EOr p, A arg)
    {
      jlc.lib.javalette.Absyn.Expr expr_1 = p.expr_1.accept(this, arg);
      jlc.lib.javalette.Absyn.Expr expr_2 = p.expr_2.accept(this, arg);
      return new jlc.lib.javalette.Absyn.EOr(expr_1, expr_2);
    }

    /* AddOp */
    public jlc.lib.javalette.Absyn.AddOp visit(jlc.lib.javalette.Absyn.Plus p, A arg)
    {
      return new jlc.lib.javalette.Absyn.Plus();
    }
    public jlc.lib.javalette.Absyn.AddOp visit(jlc.lib.javalette.Absyn.Minus p, A arg)
    {
      return new jlc.lib.javalette.Absyn.Minus();
    }

    /* MulOp */
    public jlc.lib.javalette.Absyn.MulOp visit(jlc.lib.javalette.Absyn.Times p, A arg)
    {
      return new jlc.lib.javalette.Absyn.Times();
    }
    public jlc.lib.javalette.Absyn.MulOp visit(jlc.lib.javalette.Absyn.Div p, A arg)
    {
      return new jlc.lib.javalette.Absyn.Div();
    }
    public jlc.lib.javalette.Absyn.MulOp visit(jlc.lib.javalette.Absyn.Mod p, A arg)
    {
      return new jlc.lib.javalette.Absyn.Mod();
    }

    /* RelOp */
    public jlc.lib.javalette.Absyn.RelOp visit(jlc.lib.javalette.Absyn.LTH p, A arg)
    {
      return new jlc.lib.javalette.Absyn.LTH();
    }
    public jlc.lib.javalette.Absyn.RelOp visit(jlc.lib.javalette.Absyn.LE p, A arg)
    {
      return new jlc.lib.javalette.Absyn.LE();
    }
    public jlc.lib.javalette.Absyn.RelOp visit(jlc.lib.javalette.Absyn.GTH p, A arg)
    {
      return new jlc.lib.javalette.Absyn.GTH();
    }
    public jlc.lib.javalette.Absyn.RelOp visit(jlc.lib.javalette.Absyn.GE p, A arg)
    {
      return new jlc.lib.javalette.Absyn.GE();
    }
    public jlc.lib.javalette.Absyn.RelOp visit(jlc.lib.javalette.Absyn.EQU p, A arg)
    {
      return new jlc.lib.javalette.Absyn.EQU();
    }
    public jlc.lib.javalette.Absyn.RelOp visit(jlc.lib.javalette.Absyn.NE p, A arg)
    {
      return new jlc.lib.javalette.Absyn.NE();
    }
}
