// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette;

/** Fold Visitor */
public abstract class FoldVisitor<R,A> implements AllVisitor<R,A> {
    public abstract R leaf(A arg);
    public abstract R combine(R x, R y, A arg);

/* Prog */
    public R visit(jlc.lib.javalette.Absyn.Program p, A arg) {
      R r = leaf(arg);
      for (jlc.lib.javalette.Absyn.TopDef x : p.listtopdef_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* TopDef */
    public R visit(jlc.lib.javalette.Absyn.FnDef p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      for (jlc.lib.javalette.Absyn.Arg x : p.listarg_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      r = combine(p.blk_.accept(this, arg), r, arg);
      return r;
    }

/* Arg */
    public R visit(jlc.lib.javalette.Absyn.Argument p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      return r;
    }

/* Blk */
    public R visit(jlc.lib.javalette.Absyn.Block p, A arg) {
      R r = leaf(arg);
      for (jlc.lib.javalette.Absyn.Stmt x : p.liststmt_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* Stmt */
    public R visit(jlc.lib.javalette.Absyn.Empty p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.BStmt p, A arg) {
      R r = leaf(arg);
      r = combine(p.blk_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Decl p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      for (jlc.lib.javalette.Absyn.Item x : p.listitem_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Ass p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Incr p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Decr p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Ret p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.VRet p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Cond p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.stmt_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.CondElse p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.stmt_1.accept(this, arg), r, arg);
      r = combine(p.stmt_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.While p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      r = combine(p.stmt_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.SExp p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* Item */
    public R visit(jlc.lib.javalette.Absyn.NoInit p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Init p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }

/* Type */
    public R visit(jlc.lib.javalette.Absyn.Int p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Doub p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Bool p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Void p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Fun p, A arg) {
      R r = leaf(arg);
      r = combine(p.type_.accept(this, arg), r, arg);
      for (jlc.lib.javalette.Absyn.Type x : p.listtype_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }

/* Expr */
    public R visit(jlc.lib.javalette.Absyn.EVar p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.ELitInt p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.ELitDoub p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.ELitTrue p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.ELitFalse p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.EApp p, A arg) {
      R r = leaf(arg);
      for (jlc.lib.javalette.Absyn.Expr x : p.listexpr_)
      {
        r = combine(x.accept(this, arg), r, arg);
      }
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.EString p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Neg p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Not p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.EMul p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.mulop_.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.EAdd p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.addop_.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.ERel p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.relop_.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.EAnd p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.EOr p, A arg) {
      R r = leaf(arg);
      r = combine(p.expr_1.accept(this, arg), r, arg);
      r = combine(p.expr_2.accept(this, arg), r, arg);
      return r;
    }

/* AddOp */
    public R visit(jlc.lib.javalette.Absyn.Plus p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Minus p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* MulOp */
    public R visit(jlc.lib.javalette.Absyn.Times p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Div p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.Mod p, A arg) {
      R r = leaf(arg);
      return r;
    }

/* RelOp */
    public R visit(jlc.lib.javalette.Absyn.LTH p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.LE p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.GTH p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.GE p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.EQU p, A arg) {
      R r = leaf(arg);
      return r;
    }
    public R visit(jlc.lib.javalette.Absyn.NE p, A arg) {
      R r = leaf(arg);
      return r;
    }


}
