// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette.Absyn;

public class ArrLen  extends Expr {
  public final Expr expr_;
  public final String ident_;
  public ArrLen(Expr p1, String p2) { expr_ = p1; ident_ = p2; }

  public <R,A> R accept(jlc.lib.javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof jlc.lib.javalette.Absyn.ArrLen) {
      jlc.lib.javalette.Absyn.ArrLen x = (jlc.lib.javalette.Absyn.ArrLen)o;
      return this.expr_.equals(x.expr_) && this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.expr_.hashCode())+this.ident_.hashCode();
  }


}
