// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette.Absyn;

public class ArrType  extends Type {
  public final Type type_;
  public ArrType(Type p1) { type_ = p1; }

  public <R,A> R accept(jlc.lib.javalette.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof jlc.lib.javalette.Absyn.ArrType) {
      jlc.lib.javalette.Absyn.ArrType x = (jlc.lib.javalette.Absyn.ArrType)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
