// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette.Absyn;

public class EApp  extends Expr {
  public final String ident_;
  public final ListExpr listexpr_;
  public EApp(String p1, ListExpr p2) { ident_ = p1; listexpr_ = p2; }

  public <R,A> R accept(jlc.lib.javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof jlc.lib.javalette.Absyn.EApp) {
      jlc.lib.javalette.Absyn.EApp x = (jlc.lib.javalette.Absyn.EApp)o;
      return this.ident_.equals(x.ident_) && this.listexpr_.equals(x.listexpr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listexpr_.hashCode();
  }


}
