// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette.Absyn;

public class ForEach  extends Stmt {
  public final Type type_;
  public final String ident_;
  public final Expr expr_;
  public final Stmt stmt_;
  public ForEach(Type p1, String p2, Expr p3, Stmt p4) { type_ = p1; ident_ = p2; expr_ = p3; stmt_ = p4; }

  public <R,A> R accept(jlc.lib.javalette.Absyn.Stmt.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    
    if (this == o) return true;
    if (o instanceof jlc.lib.javalette.Absyn.ForEach) {
      jlc.lib.javalette.Absyn.ForEach x = (jlc.lib.javalette.Absyn.ForEach)o;
      return this.type_.equals(x.type_) && this.ident_.equals(x.ident_) && this.expr_.equals(x.expr_) && this.stmt_.equals(x.stmt_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(37*(this.type_.hashCode())+this.ident_.hashCode())+this.expr_.hashCode())+this.stmt_.hashCode();
  }


}
