// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette.Absyn;

public class Fun  extends Type {
  public final Type type_;
  public final ListType listtype_;
  public Fun(Type p1, ListType p2) { type_ = p1; listtype_ = p2; }

  public <R,A> R accept(jlc.lib.javalette.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof jlc.lib.javalette.Absyn.Fun) {
      jlc.lib.javalette.Absyn.Fun x = (jlc.lib.javalette.Absyn.Fun)o;
      return this.type_.equals(x.type_) && this.listtype_.equals(x.listtype_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.listtype_.hashCode();
  }


}
