// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette.Absyn;

public class Neg  extends Expr {
  public final Expr expr_;
  public Neg(Expr p1) { expr_ = p1; }

  public <R,A> R accept(jlc.lib.javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof jlc.lib.javalette.Absyn.Neg) {
      jlc.lib.javalette.Absyn.Neg x = (jlc.lib.javalette.Absyn.Neg)o;
      return this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return this.expr_.hashCode();
  }


}
