// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette.Absyn;

public class NewArr  extends Expr {
  public final BaseType basetype_;
  public final Expr expr_;
  public NewArr(BaseType p1, Expr p2) { basetype_ = p1; expr_ = p2; }

  public <R,A> R accept(jlc.lib.javalette.Absyn.Expr.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof jlc.lib.javalette.Absyn.NewArr) {
      jlc.lib.javalette.Absyn.NewArr x = (jlc.lib.javalette.Absyn.NewArr)o;
      return this.basetype_.equals(x.basetype_) && this.expr_.equals(x.expr_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.basetype_.hashCode())+this.expr_.hashCode();
  }


}
