// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette.Absyn;

public abstract class Stmt implements java.io.Serializable {
  public abstract <R,A> R accept(Stmt.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(jlc.lib.javalette.Absyn.Empty p, A arg);
    public R visit(jlc.lib.javalette.Absyn.BStmt p, A arg);
    public R visit(jlc.lib.javalette.Absyn.Decl p, A arg);
    public R visit(jlc.lib.javalette.Absyn.Ass p, A arg);
    public R visit(jlc.lib.javalette.Absyn.ArrAss p, A arg);
    public R visit(jlc.lib.javalette.Absyn.ArrAssExpr p, A arg);
    public R visit(jlc.lib.javalette.Absyn.ForEach p, A arg);
    public R visit(jlc.lib.javalette.Absyn.ArrIncr p, A arg);
    public R visit(jlc.lib.javalette.Absyn.ArrDecr p, A arg);
    public R visit(jlc.lib.javalette.Absyn.Incr p, A arg);
    public R visit(jlc.lib.javalette.Absyn.Decr p, A arg);
    public R visit(jlc.lib.javalette.Absyn.Ret p, A arg);
    public R visit(jlc.lib.javalette.Absyn.VRet p, A arg);
    public R visit(jlc.lib.javalette.Absyn.Cond p, A arg);
    public R visit(jlc.lib.javalette.Absyn.CondElse p, A arg);
    public R visit(jlc.lib.javalette.Absyn.While p, A arg);
    public R visit(jlc.lib.javalette.Absyn.SExp p, A arg);

  }

}
