// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette.Absyn;

public class TypeBase  extends Type {
  public final BaseType basetype_;
  public TypeBase(BaseType p1) { basetype_ = p1; }

  public <R,A> R accept(jlc.lib.javalette.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof jlc.lib.javalette.Absyn.TypeBase) {
      jlc.lib.javalette.Absyn.TypeBase x = (jlc.lib.javalette.Absyn.TypeBase)o;
      return this.basetype_.equals(x.basetype_);
    }
    return false;
  }

  public int hashCode() {
    return this.basetype_.hashCode();
  }


}
