// File generated by the BNF Converter (bnfc 2.9.5).

package jlc.lib.javalette.Absyn;

public class Void  extends BaseType {
  public Void() { }

  public <R,A> R accept(jlc.lib.javalette.Absyn.BaseType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(java.lang.Object o) {
    if (this == o) return true;
    if (o instanceof jlc.lib.javalette.Absyn.Void) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
